export const members = [
  {
    id: 1,
    name: "권동희",
    englishName: "DongheeKwon",
    github: "hamxxn",
    gender: "female",
    role: "OB",
    codeReviewGroup: 1,
    age: 23,
  },
  {
    id: 2,
    name: "김어진",
    englishName: "EojinKim",
    github: "eojindesu",
    gender: "female",
    role: "YB",
    codeReviewGroup: 2,
    age: 24,
  },
  {
    id: 3,
    name: "김윤지",
    englishName: "YoonjiKim",
    github: "yooncandooit",
    gender: "female",
    role: "YB",
    codeReviewGroup: 7,
    age: 21,
  },
  {
    id: 4,
    name: "민경빈",
    englishName: "GyeongBinMin",
    github: "gyeongbibin",
    gender: "male",
    role: "YB",
    codeReviewGroup: 6,
    age: 25,
  },
  {
    id: 5,
    name: "박소현",
    englishName: "SohyunPark",
    github: "Sohyunnnn",
    gender: "female",
    role: "YB",
    codeReviewGroup: 8,
    age: 24,
  },
  {
    id: 6,
    name: "박원",
    englishName: "WonPark",
    github: "wonpark1",
    gender: "female",
    role: "YB",
    codeReviewGroup: 7,
    age: 22,
  },
  {
    id: 7,
    name: "박진석",
    englishName: "JinSeokPark",
    github: "jin-evergreen",
    gender: "male",
    role: "YB",
    codeReviewGroup: 3,
    age: 23,
  },
  {
    id: 8,
    name: "배정민",
    englishName: "JeongminBae",
    github: "qowjdals23",
    gender: "female",
    role: "YB",
    codeReviewGroup: 4,
    age: 24,
  },
  {
    id: 9,
    name: "백지연",
    englishName: "JiyeonBaek",
    github: "jyeon03",
    gender: "female",
    role: "YB",
    codeReviewGroup: 3,
    age: 23,
  },
  {
    id: 10,
    name: "손하은",
    englishName: "HaeunSon",
    github: "sonnnnhe",
    gender: "female",
    role: "YB",
    codeReviewGroup: 8,
    age: 23,
  },
  {
    id: 11,
    name: "송민하",
    englishName: "MinhaSong",
    github: "sminha",
    gender: "female",
    role: "YB",
    codeReviewGroup: 5,
    age: 26,
  },
  {
    id: 12,
    name: "양승혜",
    englishName: "SeunghyeYang",
    github: "seunghye-rain",
    gender: "female",
    role: "YB",
    codeReviewGroup: 1,
    age: 26,
  },
  {
    id: 13,
    name: "엄경호",
    englishName: "KyounghoEom",
    github: "maehwasoo",
    gender: "male",
    role: "OB",
    codeReviewGroup: 9,
    age: 26,
  },
  {
    id: 14,
    name: "오수빈",
    englishName: "SubinOh",
    github: "odukong",
    gender: "female",
    role: "YB",
    codeReviewGroup: 4,
    age: 24,
  },
  {
    id: 15,
    name: "이채영",
    englishName: "ChaeyeongYi",
    github: "hummingbbird",
    gender: "female",
    role: "YB",
    codeReviewGroup: 5,
    age: 24,
  },
  {
    id: 16,
    name: "이현준",
    englishName: "HyunJunLee",
    github: "leeeehyunjun",
    gender: "male",
    role: "OB",
    codeReviewGroup: 7,
    age: 26,
  },
  {
    id: 17,
    name: "이훈진",
    englishName: "HunjinLee",
    github: "huniversal",
    gender: "male",
    role: "YB",
    codeReviewGroup: 4,
    age: 25,
  },
  {
    id: 18,
    name: "임나은",
    englishName: "NaeunLim",
    github: "eunkr82",
    gender: "female",
    role: "YB",
    codeReviewGroup: 2,
    age: 22,
  },
  {
    id: 19,
    name: "임서준",
    englishName: "SeojoonLim",
    github: "jm8468",
    gender: "male",
    role: "YB",
    codeReviewGroup: 1,
    age: 26,
  },
  {
    id: 20,
    name: "임지성",
    englishName: "JisungLim",
    github: "jstar000",
    gender: "male",
    role: "OB",
    codeReviewGroup: 2,
    age: 26,
  },
  {
    id: 21,
    name: "임지수",
    englishName: "JisooLim",
    github: "jisooooooooooo",
    gender: "female",
    role: "OB",
    codeReviewGroup: 3,
    age: 25,
  },
  {
    id: 22,
    name: "장민수",
    englishName: "MinsuJang",
    github: "Tnalxmsk",
    gender: "male",
    role: "YB",
    codeReviewGroup: 8,
    age: 27,
  },
  {
    id: 23,
    name: "장정훈",
    englishName: "JeonghoonJang",
    github: "jeonghoon11",
    gender: "male",
    role: "OB",
    codeReviewGroup: 5,
    age: 25,
  },
  {
    id: 24,
    name: "정유진",
    englishName: "YujinJung",
    github: "hello-yujin",
    gender: "female",
    role: "YB",
    codeReviewGroup: 5,
    age: 23,
  },
  {
    id: 25,
    name: "조혜린",
    englishName: "HyerinCho",
    github: "jogpfls",
    gender: "female",
    role: "OB",
    codeReviewGroup: 6,
    age: 22,
  },
  {
    id: 26,
    name: "지민재",
    englishName: "MinjaeJi",
    github: "mimizae",
    gender: "female",
    role: "YB",
    codeReviewGroup: 6,
    age: 23,
  },
  {
    id: 27,
    name: "차주영",
    englishName: "JuyoungCha",
    github: "verynicetomato",
    gender: "female",
    role: "YB",
    codeReviewGroup: 3,
    age: 24,
  },
  {
    id: 28,
    name: "최윤하",
    englishName: "YoonhaChoi",
    github: "twossu",
    gender: "female",
    role: "YB",
    codeReviewGroup: 7,
    age: 23,
  },
];

if (!localStorage.getItem("membersData")) {
  localStorage.setItem("membersData", JSON.stringify(members));
}
